import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Image from 'next/image';
import styles from '../styles/About.module.scss';
import { FaHtml5, FaCss3, FaBootstrap, FaGithub, FaSass } from 'react-icons/fa';
import {
	SiJavascript,
	SiReact,
	SiJquery,
	SiNextdotjs,
	SiNodedotjs,
	SiExpress,
} from 'react-icons/si';

const About = () => {
	return (
		<>
			<Head>
				<title>About Page</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<main className={styles.main}>
				<section className={styles.section_one}>
					<div className={styles.section_container}>
						<div className={styles.section_one_image_container}>
							<Image
								priority
								className={styles.section_one_image}
								src='/images/about/profile-color.jpg'
								alt='Mark Rose smiling in color'
								layout='fill'
							/>
						</div>
						<div className={styles.section_one_text_container}>
							<h1>About Me</h1>
							<p>
								Lorem ipsum dolor sit amet consectetur adipisicing elit.
								Eveniet, ad voluptatibus nemo est mollitia totam obcaecati. Rem
								et veritatis eum!
							</p>
						</div>
					</div>
				</section>

				<section className={styles.section_two}>
					<div className={styles.section_container}>
						<div className={styles.section_two_text_container}>
							<h1>A Little More About Me</h1>
							<p>
								Lorem ipsum dolor sit amet consectetur adipisicing elit.
								Eveniet, ad voluptatibus nemo est mollitia totam obcaecati. Rem
								et veritatis eum!
							</p>
							<p>
								Lorem, ipsum dolor sit amet consectetur adipisicing elit.
								Dolorum, velit placeat magnam ullam autem nulla sit saepe
								voluptate nostrum sed. Perspiciatis quisquam magni voluptate rem
								dicta ullam quae eveniet pariatur!
							</p>
						</div>
						<div className={styles.section_two_image_container}>
							{/* <Image className={styles.section_two_image} /> */}
						</div>
					</div>
				</section>

				<section className={styles.section_three}>
					<div className={styles.section_container}>
						<h1>Languages I Know</h1>
						<div className={styles.language_logo_container}>
							<p>
								<FaHtml5 />
							</p>
							<p>
								<FaCss3 />
							</p>
							<p>
								<FaSass />
							</p>
							<p>
								<FaBootstrap />
							</p>
							<p>
								<SiJavascript />
							</p>
							<p>
								<SiJquery />
							</p>
							<p>
								<SiReact />
							</p>
							<p>
								<SiExpress />
							</p>
							<p>
								<SiNextdotjs />
							</p>
							<p>
								<SiNodedotjs />
							</p>
							<p>
								<FaGithub />
							</p>
						</div>
					</div>
				</section>
			</main>

			<Footer />
		</>
	);
};

export default About;
